name: Deployment

on:
  push:
    tags:
      - v*.*.*

jobs:
  # Deploy release
  deploy:
    runs-on: ubuntu-18.04
    container: johnmcfarlane/cnl_ci:gcc-10
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    - name: Deploy
      shell: bash
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: CNL_VERSION_TAG=$GITHUB_REF $GITHUB_WORKSPACE/.github/deploy
